### ISSUE TITLE
Set it up perfectly, but the picture doesn't actually get uploaded and I don't get the right link

### ISSUE THREAD

**Issue by djosepaci** [JoeGandy/ShareX-Custom-Upload#10]
Hi! Let me just start by saying I love this stuff, and I find it really useful since I'm trying to get my own image uploader without Imgur taking ages to upload and then compressing stuff. So... Thank you so much!

There's only two issues, though; I set everything perfectly, and when I capture a region and send it through the custom destination thingy, I get the HTML code of my index page as the URL!

Sounds weird, isn't it? But the weird part is, it tells me the file was uploaded but I can't see it on my server.

What did I do wrong? Is there something I need to set in the PHP settings themselves?

**Comment by TheLovinator1** [comment]
Try to change **upload_max_filesize** and **post_max_size** in your **php.ini**. I am using 0M on both. I have no idea if it is bad to use 0M so try to search around first before you use it.


([post_max_size must be larger or equal to upload_max_filesize](https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size/2184541#2184541))

**Comment by djosepaci** [comment]
I set 'em both to 0M, still have issues :/ ShareX gives the "ok the file is uploaded" yet I still get the same outcomes.

**Comment by HenkSpenk19** [comment]
Same thing here. Also It looks like your ignore variable is not working ; )

**Comment by JoeGandy** [comment]
If you are getting the index.html, you're hitting one of the redirects, check folder permissions on where it's uploading. 

If you're still having no luck send over your config.php (sanatise the private keys)

**Comment by matthewvvliet** [comment]
I'm also trying this out but when I hit Image Uploader test, it returns me the upload.php content in the 'Test result'

**Comment by JoeGandy** [comment]
I will look at anyones config.php if they need help, Else I'm open to to pull requests that make errors more clear in the future

**Comment by JoeGandy** [comment]
No further comments provided on config.php, so I'll close this for now, anyone facing this issue. Start a new issue, with the following:

- Screenshot of your config.php (remove any sensitive info)
- Your php error log
- ShareX errorlog
- Screenshot of your ShareX settings for this custom uploader.

Thanks,

Joe
