### ISSUE TITLE
Merge PRs

### ISSUE THREAD

**Issue by theaquarium** [JoeGandy/ShareX-Custom-Upload#108]
Hi,

There hasn't been much progress on the recent PRs left on the repo and I was wondering whether it would be possible to get them merged soon. One of the PRs adds updater functionality and I wanted to try to get this feature out before releasing a new version, since there are a couple fixes in master right now that should be released.

**Comment by JoeGandy** [comment]
Yep that's on me, I'd pretend I was busy, but I've been getting more complacent with maintaining the project, I'll try stay on it, but in the mean time any other contributors feel free to jump in ! 👍
