### ISSUE TITLE
500 webserver error

### ISSUE THREAD

**Issue by zkp12** [JoeGandy/ShareX-Custom-Upload#109]
Hello currently I'm trying to install 2.0.1
I used to have 1.0.0 but I decided to upgrade since it had problems while it had 777 perms it said it didnt so I decided to switch
Now on I.expample.com but I got that and I have set it up correctly so I dont know why this is happening

**Comment by zkp12** [comment]
its a completly fresh install on a new domain

**Comment by theaquarium** [comment]
Could you send your configuration and the server's error logs?

Also, please make sure that you have the `openssl` and `fileinfo` extensions enabled in your `php.ini` and that `mod_rewrite` and `mod_authz_core` are enabled in your `httpd.conf`

**Comment by zkp12** [comment]
I dont like to share that sensitive info In public

Op vr 14 aug. 2020 17:47 schreef Peter Vashevko <notifications@github.com>:

**Comment by theaquarium** [comment]
I'm not asking to share your domain and secret key. But it should be fine even without the configuraton. Can you check that the extensions I mentioned are enabled and could you check your error log to see if there are any issues? A 500 error means that there is a server error, so I may not be able to help without knowing what the error is. 

Can you also clarify the page you are on when you get the error?

**Comment by JoeGandy** [comment]
as @theaquarium proving your configs helps us loads, feel free to remove domains, secrets from it first!

500 errors will have errors in your log, apache or nginx, so check them.

We'll close until we get a bit more to go off.
