### ISSUE TITLE
Gallery Not Working

### ISSUE THREAD

**Issue by El1teZombiezHD** [JoeGandy/ShareX-Custom-Upload#11]
Got your script working and is great! However your gallery doesn't seem to be working.
I can access the 'index.php' page and has no table with no images in there.

https://i.imgur.com/QtBiJ5G.png

That is a screenshot of what I see. There are files and screenshots in the folder however it isn't displaying them

**Comment by ToniTurnerr** [comment]
Are you sure you added your IP correctly to the config?

**Comment by JoeGandy** [comment]
Hi, as Toni said, check the allowed_ips in config.php
