### ISSUE TITLE
Upload error: your file is larger than the upload_max_filesize set in your php.ini

### ISSUE THREAD

**Issue by woozy404** [JoeGandy/ShareX-Custom-Upload#110]
When trying to upload an mp4 or gif that is more than a few seconds long this error appears, ive tried to fix it but cannot see where.. Any help would be appreciated 

Upload error: your file is larger than the upload_max_filesize set in your php.ini.

**Comment by JoeGandy** [comment]
Hi,
Yeah this will be the settings in php
`upload_max_filesize`, post_max_size`, `memory_limit`

You can update these directly on your server, I'll see what i can do about making the error message more clear.

**Comment by woozy404** [comment]
Hi! Thanks for the quick reply but, I'm still having issues finding where that file is, I must be missing the obvious here.. I have checked almost every file where it makes sense to be but cannot find it.

**Comment by JoeGandy** [comment]
Hi, yep its varies system to system, have a look at:

https://devanswers.co/ubuntu-php-php-ini-configuration-file/#:~:text=ini%20is%20usually%20located%20in,ini%20.

**Comment by woozy404** [comment]
Thanks! That seemed to do the trick!
