### ISSUE TITLE
Unable to access uploads?

### ISSUE THREAD

**Issue by silent** [JoeGandy/ShareX-Custom-Upload#114]
I been using this for a while and haven't made any changes to my website in months and all of a sudden it just started acting up.
I have tried a new installation of the files, looked into my server configuration, and still unsure what is causing this issue.

Errors from my log:
[Fri Sep 11 23:25:47.176228 2020] [authz_core:error] [pid 1866610] [client REDACTED] AH01630: client denied by server configuration: /home/REDACTED/public_html/u/u/YB1jwi.png
[Fri Sep 11 23:07:08.412614 2020] [core:alert] [pid 1815753] [client REDACTED] /home/REDACTED/public_html/u/.htaccess: <Directory not allowed here

If I screenshot anything, it'll upload but unable to see it on the site due to it displaying "File not found."
If I visit https://website.com/u/ it'll redirect to website.com/u/register and also display "File not found." but if I go to website.com/u/register.php it loads fine. So I am really confused.

**Comment by JoeGandy** [comment]
What perms are set on your files? I guess if the files are being created its probably fine?

It could also be redirects being a bit wonk in your htaccess/apache settings, but i use nginx so can't share what i have.

**Comment by silent** [comment]
Seems like it fixed itself. I am really confused but whatever.
