### ISSUE TITLE
Error saving username and password.

### ISSUE THREAD

**Issue by noobitaz** [JoeGandy/ShareX-Custom-Upload#116]
Panel works fine, but if I try to create an account it says "Error saving username and password.".

**Comment by theaquarium** [comment]
Can you check your PHP `error.log` to see if there are any errors?

**Comment by noobitaz** [comment]
@theaquarium Hello. I checked, it's empty.

**Comment by theaquarium** [comment]
Can you please make sure that the directory where your uploader is stored is writable? If there is already a `login.json` file, can you delete it and try making an account again?

**Comment by noobitaz** [comment]
@theaquarium I've executed chmod -R 775 to main uploader directory and I've never made an account, so there is no login.json file.

**Comment by noobitaz** [comment]
It's most likely web server issue, if others haven't faced that problem. I'm new to all this so I'm not sure what I should check.

**Comment by theaquarium** [comment]
Yeah, I'm also not really sure what it could be. If you're getting that error, there's one specific bit of code that's failing, which is the file write of the login info. My only advice is to make sure that your webserver process/account also has write access to the directory.
