### ISSUE TITLE
Users stored file location

### ISSUE THREAD

**Issue by woozy404** [JoeGandy/ShareX-Custom-Upload#118]
Hello! 

After registering an account where can it be stored? 

I accidentally made one and i'm trying to delete it because I use IP whitelist more.

Thanks!

**Comment by theaquarium** [comment]
Just delete the file called `login.json` to reset your account. You can also just turn off password login and then your account will just be ignored.

**Comment by woozy404** [comment]
Thanks!

I turned on login with password and w/out user just to see how it worked, turned those off already just looking to delete it
