### ISSUE TITLE
Forbidden Error

### ISSUE THREAD

**Issue by OofChair** [JoeGandy/ShareX-Custom-Upload#127]
Hi, whenever I go to my domain, I get a Forbidden error. I don't have any IP blocking

**Comment by davwheat** [comment]
You haven't set up Apache properly in your system config file (`/etc/apache2/apache2.conf`).

**Comment by OofChair** [comment]
> You haven't set up Apache properly in your system config file (`/etc/apache2/apache2.conf`).

I did that, but maybe this made it go wrong:
Instead of setting it to the directory with the release folder, I made the website to be inside the release folder. Should I not have done that?
