### ISSUE TITLE
Can't see my gallery

### ISSUE THREAD

**Issue by SimonMattila** [JoeGandy/ShareX-Custom-Upload#13]
As title says, I can't see my gallery, only thing that shows up is 

"**Uploading Site**
Free space: 104.18 GB / 733.18 GB"

Any idea to make it show up? Or am I just stupid?
`    'allowed_ips' => array('192.168.0.0', '0.0.0.0'),`
^ standard settings for IPs, hosted online, accessing from my own PC

**Comment by JoeGandy** [comment]
So by default I have it set so it will lock down the site, as I imagined most people would set this up as a personal upload site.

See the comment above the config:
`/* This is a list of IPs that can access the gallery page (Leave empty for universal access) */`

So if your site is hosted publicly but you want to restrict access to just you, add your home IP
If you want anyone to be able to access your site, just remove the items from the array so
`'allowed_ips' => array('192.168.0.0', '0.0.0.0'),`
would become
`'allowed_ips' => array(),`
