### ISSUE TITLE
Twitter and Google Photos

### ISSUE THREAD

**Issue by dominikpflegerl** [JoeGandy/ShareX-Custom-Upload#139]
As for now, it seems ShareX uploads picture embedded into a Tweet or photos from Google Photos as .txt

Example: https://twitter.com/nywolforg/status/1351940301703753728
Result: https://i.neus.xyz/v0OTHz.txt

I took a short look into the php files, and when I change 

```
    if (!isset($extension) || $extension === null || $extension === '') {
        $extension = 'txt';
    }
```

Now, the URL for the images on Twitter are:

https://pbs.twimg.com/media/EsMOiQbXcAE-g5w?format=jpg&name=small

and logically the scripts uploads it as .txt as there is no extension.

Now, I just thought, maybe a simple URL if check would solve this, but does the script get the URL from ShareX, or just a file from ShareX?

**Comment by davwheat** [comment]
The server doesn't support uploading an image via URL. It's designed to handle file uploads.

ShareX is just sending the server text, which is interpreted as a text file upload.
