### ISSUE TITLE
Uploader returns 500 error

### ISSUE THREAD

**Issue by adam-gre** [JoeGandy/ShareX-Custom-Upload#14]
Hi, sorry to make a new topic when there's one already for this issue but that one doesnt have a solution and has been closed.

My webpage returns a 500 error when I try to upload using these settings:
https://i.imgur.com/8n63hCV.png
https://i.imgur.com/3SfZgAf.png

Error log: https://i.imgur.com/0EfccPX.png

All help appreciated

Adam

**Comment by JoeGandy** [comment]
Do you have your php error log you could provide too?
Does just navigating to your page work?
