### ISSUE TITLE
Suggestion: Add discord embeds

### ISSUE THREAD

**Issue by Smugaski2** [JoeGandy/ShareX-Custom-Upload#144]
Hi, Could you add discord embeds like this to the uploader?
![image](https://user-images.githubusercontent.com/78426042/110133013-af6a3500-7dc3-11eb-9bb6-7379636b2b74.png)

**Comment by davwheat** [comment]
That's not possible by default as we directly serve the files. Instead another endpoint would be needed, such as `example.com/file.png/embed` which *could* provide this.

**Comment by theaquarium** [comment]
Duplicate of #126.
