### ISSUE TITLE
Allowing for use with custom URL

### ISSUE THREAD

**Issue by Soitora** [JoeGandy/ShareX-Custom-Upload#15]
Hey again

I use `domain.abc` to upload atm but I have gotten another url that's shorter (`domain.xyz`) and better but cannot be used as the primary url. I tried following [ShareX Custom Uploader Official Guide](https://getsharex.com/docs/custom-uploader) to get my `domain.abc/image` output as `domain.xyz/image` using several of the mentioned stuff.

The method I want to work right now is using `domain.xyz/$response$` in URL field , but `$response$` outputs the entire `domain.abc/image` URL, so if I try `domain.xyz/$response$` I get `domain.xyz/domain.abc/image`

I am tired so might be bad at explaining but sincerely hope you understand me.
Sincerely, Simon

**Comment by JoeGandy** [comment]
I would suggest following the guide on the main readme in this repo, It should cover all the steps and varies a little from the officially configuration. 

If anything isn't clear give me a shout.

**Comment by Soitora** [comment]
Ahh I realise I'm dumb now! 

I went to config.php and made output_url empty, that way the script only output IMAGE-Name.png to ShareX, which made me able to use `domain.xyz/$response$` for a custom domain!

**Comment by JoeGandy** [comment]
Great I'm glad you sorted it :+1:
