### ISSUE TITLE
Webpage not loading on Firefox

### ISSUE THREAD

**Issue by Aqua-22** [JoeGandy/ShareX-Custom-Upload#152]
When i try to go to my upload page it hangs and doesn't do anything but on chrome it works fine. I just installed it today.

**Comment by Aqua-22** [comment]
@JoeGandy I can't seem to make it work. I don't know if u even see this.

**Comment by davwheat** [comment]
I'm personally in the process of migrating from this to my own node js based upload server, so I won't be helping to maintain this repository for a while.

I have no clue why this would be the case, unless Firefox times out before other browsers and you have a large amount of files uploaded.

**Comment by JoeGandy** [comment]
I'll have a dig into this, I think Im personally running an old version of this repo since some others took up maintenance :D I will have a play around this friday

**Comment by Aqua-22** [comment]
I have two png files uploaded so that is not the issue it's just simply not loading on firefox but on chrome it works, and when I remove the line from the head tag in index.php where it loads the css the page loads but without anything and it's just a white blank page.

**Comment by itsChix** [comment]
Currently facing the same issue.

**Comment by Aqua-22** [comment]
I just noticed when the webpage hangs it tries to make a TLS handshake with cdn.jsdelivr.net.

**Comment by itsChix** [comment]
Noticed an unmerged PR that is supposed to fix this issue. https://github.com/JoeGandy/ShareX-Custom-Upload/pull/141

I'll try to merge changes on my forked version to see if this actually fixes this issue.

**Comment by Aqua-22** [comment]
> 
> 
> Noticed an unmerged PR that is supposed to fix this issue. #141
> 
> I'll try to merge changes on my forked version to see if this actually fixes this issue.

I've seen that one but I mean I got the latest version from the repo so that fix should be in there right?

**Comment by itsChix** [comment]
> > Noticed an unmerged PR that is supposed to fix this issue. #141
> > I'll try to merge changes on my forked version to see if this actually fixes this issue.
> 
> I've seen that one but I mean I got the latest version from the repo so that fix should be in there right?

Pull requests only get into the repo if the owner merges it, which means that he approves the changes and makes those modifications to the codebase. 

You have to go into the PR creator's version of the software (available at https://github.com/LordByronRS/ShareX-Custom-Upload/tree/firefox-loading-fix ) and pull the files from this repo to your server.

**Comment by Aqua-22** [comment]
Ok so I pulled the files from the fixed repo but the page still doesn't load.

**Comment by itsChix** [comment]
> Ok so I pulled the files from the fixed repo but the page still doesn't load.

Are you using Apache or Nginx?

I'll check out if it works later in the day.

**Comment by Aqua-22** [comment]
I am using Apache.

**Comment by rutkk** [comment]
Huh. I checked the exact same version and it now works. I'm running nginx btw. If you want I can DM you the link to the site.

**Comment by Aqua-22** [comment]
Sure! If you tell me where i can dm you i'll send it over!

**Comment by Aqua22** [comment]
Sure! When I get infront of my pc i will try to switch over to nginx then.

**Comment by rutkk** [comment]
The issue got fixed in the most recent public version. Download the fixed one off of here: https://github.com/JoeGandy/ShareX-Custom-Upload/archive/refs/heads/master.zip

**Comment by Aqua22** [comment]
Ok. I will check it out when i put everything back together because i just moved.

**Comment by Aqua22** [comment]
So I pulled the fixed version and now it works! Thanks to everyone who commented!
