### ISSUE TITLE
Gallery IP's

### ISSUE THREAD

**Issue by Joe-Alderdice** [JoeGandy/ShareX-Custom-Upload#18]
The only way I can access my gallery is by making it totally open..
I've added every IP it could possibly be: myexternalip, my ipv4ip, 127.0.0.1. Everything, and yet I can only view it if its got no IP's in the field. I really want the gallery to be private..

**Comment by Reece4504** [comment]
Try IPv6 address (google "What is my IPv6" since when I try PHP normally returns my v6 address)

**Comment by Natfan** [comment]
Maybe try checking your website logs for the IP that they connect to? My IP list is stored under /var/logs/apache/access.log.1, but yours may be different.
