### ISSUE TITLE
Returing HTML?

### ISSUE THREAD

**Issue by 615283** [JoeGandy/ShareX-Custom-Upload#19]
Sometimes when recording videos, not a URL is returned, but the HTML of my webpage that the php is set to redirect normal requests to. Any idea why?

**Comment by 615283** [comment]
Bump

**Comment by JoeGandy** [comment]
Hey,

This often happens when you are hitting the PHP max upload limit on your server.

Which makes sense why its happening with larger files like videos.

**Comment by 615283** [comment]
Thanks @Natfan that helped alot!

**Comment by Natfan** [comment]
[alot!](https://react.natfan.io/alot/)
