### ISSUE TITLE
Gallery doesn't show

### ISSUE THREAD

**Issue by winnipeg21** [JoeGandy/ShareX-Custom-Upload#22]
When i access my site via url.com/u is only shows the title.  The table isn't there :/

**Comment by DJkikisa** [comment]
In config.php
` /* This is a list of IPs that can access the gallery page (Leave empty for universal access) */
'allowed_ips' => array('192.168.0.0', '0.0.0.0'),
`

**Comment by winnipeg21** [comment]
Sorry for the delayed response, I have my config allowed_ips empty just like you. I'm receiving the header text and nothing else. All files have been changed to set to /img instead of /u. I'm also using cloudflare which can be an issue running scripts.

http://winnipeg21.xyz/img

**Comment by DJkikisa** [comment]
I'm using cloudflare too, it would be problem only if you use allowed ips. Intresting is that i just downloaded full non edited script edited only allowed_ips line and all was working. And have you edited upload.php so it uploads to /img/ not /u/ ?

**Comment by winnipeg21** [comment]
Everything works expect the gallery aspect doesn't appear

**Comment by DJkikisa** [comment]
Doesn't load main.js in js folder :)

**Comment by winnipeg21** [comment]
That could be something bad

**Comment by winnipeg21** [comment]
So in the index.php I switched it from js/main.js ==> img/js/main.js. That didn't work. So then I switched it to /js/main.js.

**Comment by DJkikisa** [comment]
You can always put main.js content in index.php, not best but if you can't load main.js that would fix it:
`<script>
$(document).ready(function() {
    $('#example').DataTable();
    $('div.alert').delay(3000).fadeOut(500);
} );
</script>`

**Comment by winnipeg21** [comment]
I added that code line in. Still doesn't work. Just gives me a blank white screen with the heading.

**Comment by DJkikisa** [comment]
You needed replace <script src="js/main.js" type="text/javascript"></script> with that code not in head tags since jquery is loaded later and it shows error :)

**Comment by winnipeg21** [comment]
I've done that. Still nothing

**Comment by DJkikisa** [comment]
You can fully remove ip check from code:
Line 27 delete:
`if(empty($config['allowed_ips']) || in_array($_SERVER['REMOTE_ADDR'], $config['allowed_ips'])){`
And Line 54:
`<?php }?>`
And test then.

**Comment by winnipeg21** [comment]
Works! Thanks

**Comment by Natfan** [comment]
Looks like this is done, closing issue (feel free to reopen if needed!)
