### ISSUE TITLE
ShareX won't upload files

### ISSUE THREAD

**Issue by TurboCheetah** [JoeGandy/ShareX-Custom-Upload#24]
Error: Message:
Too many automatic redirections were attempted.

Request URL:
https://redacted/upload.php

`Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
`

**Comment by TurboCheetah** [comment]
Fixed.

**Comment by TurboCheetah** [comment]
Now I get `URL: Sorry, there was a problem uploading your file. (Ensure your directory has 777 permissions)`. I gave the directory the permissions and I still get it.

**Comment by TurboCheetah** [comment]
Bump

@JoeGandy @DJkikisa

**Comment by TurboCheetah** [comment]
config.php:
```php
<?php

return array(
    'secure_key' => 'redacted',

    'output_url' => 'https://i.redacted/',

    'redirect_url' => 'redacted',

    'allowed_ips' => '',

    'page_title' => 'Turbo File Host',

    'heading_text' => 'Turbo File Host',
);
?>
```
upload.php:
```php
<?php
$config = include('config.php');

$key = $config['secure_key'];
$uploadhost = $config['output_url'];
$redirect = $config['redirect_url'];

if ($_SERVER["REQUEST_URI"] == "/robot.txt") { die("User-agent: *\nDisallow: /"); }
 
if (isset($_POST['key'])) {
    if ($_POST['key'] == $key) {
        $parts = explode(".", $_FILES["d"]["name"]);
        $target = getcwd() . "/i/" . $_POST['name'] . "." . end($parts);
        if (move_uploaded_file($_FILES['d']['tmp_name'], $target)) {
            $target_parts = explode("/i/", $target);
            echo $uploadhost . end($target_parts);
        } else {
            echo "Sorry, there was a problem uploading your file. (Ensure your directory has 777 permissions)";
        }
    } else {
        header('Location: '.$redirect);
    }
} else {
    header('Location: '.$redirect);
}
?>
```

**Comment by DJkikisa** [comment]
Looks like mistake in ShareX Configuration art, since just tested and when removed name in ShareX it returned me only link with file extension. So redo ShareX Configuration Step 5 and test again :)

**Comment by TurboCheetah** [comment]
Still not working @DJkikisa...
![5ff55](https://user-images.githubusercontent.com/19479111/43051022-e69f6632-8dd7-11e8-9cef-7645650c9d65.png)

**Comment by DJkikisa** [comment]
`<?php
$config = include('config.php');

$key = $config['secure_key'];
$uploadhost = $config['output_url'];
$redirect = $config['redirect_url'];

if ($_SERVER["REQUEST_URI"] == "/robot.txt") { die("User-agent: *\nDisallow: /"); }
 
if (isset($_POST['key'])) {
    if ($_POST['key'] == $key) {
        $parts = explode(".", $_FILES["d"]["name"]);
        $target = getcwd() . "/" . $_POST['name'] . "." . end($parts);
        if (move_uploaded_file($_FILES['d']['tmp_name'], $target)) {
            $target_parts = explode("/", $target);
            echo $uploadhost . end($target_parts);
        } else {
            echo "Sorry, there was a problem uploading your file. (Ensure your directory has 777 permissions)";
        }
    } else {
        header('Location: '.$redirect);
    }
} else {
    header('Location: '.$redirect);
}
?>`

**Comment by TurboCheetah** [comment]
Thanks!
