### ISSUE TITLE
Implement the option to use a username/password on the site, using .htpassword

### ISSUE THREAD

**Issue by JoeGandy** [JoeGandy/ShareX-Custom-Upload#27]

**Comment by Natfan** [comment]
`Added base64 syntax to custom uploader parser, example syntax for authorization header: Basic $base64:username:password$`
- [ShareX 12.3.0 Changelog](https://getsharex.com/changelog/)

Looks like this idea may be more feasible.

**Comment by theaquarium** [comment]
A version of this has been added in Version 2. It doesn't use `.htpassword`, but I've added a custom login implementation.
