### ISSUE TITLE
Works with url shortener?

### ISSUE THREAD

**Issue by byEliteHacks** [JoeGandy/ShareX-Custom-Upload#3]
how to use that ? :c

**Comment by JoeGandy** [comment]
Hi, this is something I'll work on over the next week. Currently it's not in though.

**Comment by JoeGandy** [comment]
I've closed this issue, at the time of looking into it, it would take a lot more work to integrate URL shortening as it would require some kind of DB storage, so I'm closing this for now, if anyone wants to try, I'm open to seeing this implemented, I just want to try keep this the lightweight tool it is
