### ISSUE TITLE
Returning config.php on upload???

### ISSUE THREAD

**Issue by 615283** [JoeGandy/ShareX-Custom-Upload#30]
Message:
The remote server returned an error: (302) Redirect.

Request URL:
https://i.615283.net/upload.php/

Response:
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="">here</a></body>/* This is a secure key that only you should know, an added layer of security for the image upload */
  'secure_key' => '[REDACTED]',

/* This is the url your output will be, usually http://www.domain.com/u/, also going to this url will be the gallery page */
  'output_url' => 'https://i.615283.net/u/',

/* This is a redirect url if the script is accessed directly */
  'redirect_url' => 'https://www.615283.net/',

/* This is a list of IPs that can access the gallery page (Leave empty for universal access) */
  'allowed_ips' => ['192.168.0.0', '127.0.0.1'],

/* Page title of the gallery page */
  'page_title' => 'Files',

/* Heading text at the top of the gallery page */
  'heading_text' => 'Files',
  
/* Delete file option (true to enable, disabled by default) */
    'enable_delete' => false,
    
/* Show image in tooltip  (true to enable, disabled by default) */
    'enable_tooltip' = true

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by DJkikisa** [comment]
I just tested it's only happen if you remove <?php in top of config, atleast  config.php export part. And change secure_key @ end since https://i.615283.net/upload.php/ shows it for all :) About moved are you using IIS  ? If yes , then try add after each header in upload.php exit();  :)

**Comment by 615283** [comment]
I've done so, but now on line 3 of config.php (return [) I get a 500 saying unexpected [

**Comment by DJkikisa** [comment]
Are your php version older than 5.4 ? Becouse array short tags is from php 5.4.

**Comment by 615283** [comment]
Thank you so much, that's worked, any ideas as to why this happened suddenly, were there changes to the program?

**Comment by Natfan** [comment]
What did you change prior to fixing it?

**Comment by JoeGandy** [comment]
As @DJkikisa pointed out, its just that before php 5.4 arrays would look like:
`array('item one', 'item two');`
Since then we have a new short hand syntax
`['item one', 'item two']`

If you hit the second of the two types while running php < 5.4, itll throw a 500 error and break the page.
