### ISSUE TITLE
returns html

### ISSUE THREAD

**Issue by iraizo** [JoeGandy/ShareX-Custom-Upload#40]
i added the max file size for php to 40m in /etc/php/apache2/

**Comment by iraizo** [comment]
now it just returns domain/u/

**Comment by Natfan** [comment]
Could you please provide context, such as excerpts from the files you have changed and screenshots of error messages? Could you please also provide the output of [phpinfo()](https://www.php.net/manual/en/function.phpinfo.php)?

**Comment by iraizo** [comment]
this is the info https://furry-pics.club/info.php ill let this up till this is not needed anymore, my config looks like this https://hastebin.com/kahihocaro.xml these are my sharex settings: https://gyazo.com/e3931efd0664af73667980d3997b73a5 https://gyazo.com/0b38a068604e19606378912b3aa908ce
and this is the error: https://gyazo.com/dafecf79f70e2b693e463221904dab05

**Comment by DJkikisa** [comment]
Doesn't look that you have changed them in settings.
https://gyazo.com/1284ecdada4c96abb367074d15167463
https://gyazo.com/5fd7671abcb383b4f515d782514ebae4

**Comment by iraizo** [comment]
Where do I edit that tho I just find php.inis in /php/7.2/ and then apache2 folder?

**Comment by DJkikisa** [comment]
In php info shows all paths to ini files:
https://gyazo.com/85be99fd9c083b228abc8b548bcfeca2

**Comment by iraizo** [comment]
oh thanks im really new im going to edit it and gonna check if it works

**Comment by iraizo** [comment]
https://gyazo.com/c93d8ef26cbd239d81ff99a555720595 it dosent seem to update

**Comment by iraizo** [comment]
nvm apache2 restart fixed it i guess

**Comment by iraizo** [comment]
it still does the same tho
