### ISSUE TITLE
Adding IP to gallery

### ISSUE THREAD

**Issue by ghost** [JoeGandy/ShareX-Custom-Upload#41]
I've gone ahead and added my IPv6 and IPv4 to the gallery and neither are working.  Am I missing something?

**Comment by DJkikisa** [comment]
Make an extra php file and check if :
`<?php echo $_SERVER['REMOTE_ADDR']`
Dumps your ip.

**Comment by Devtodays** [comment]
na, not my ip, I'm using cloudflare. Is there a specific setting I can turn off on cloudflare to release my IP.

**Comment by DJkikisa** [comment]
Then you need add this code in index.php:
`if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
  $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
}`

**Comment by JoeGandy** [comment]
Hi, 
I've recently done some work and made it more clear what IP needs adding to the gallery, go ahead and grab the latest update and let me know if you have any trouble :)

**Comment by DJkikisa** [comment]
> Hi,
> I've recently done some work and made it more clear what IP needs adding to the gallery, go ahead and grab the latest update and let me know if you have any trouble :)

If using cloudflare need add extra check since, cloudflare gives client ip through other variable. Script what posted gives fix for it. Of course you can make extra security check to check if info comes from cloudflare servers.

**Comment by JoeGandy** [comment]
> > Hi,
> > I've recently done some work and made it more clear what IP needs adding to the gallery, go ahead and grab the latest update and let me know if you have any trouble :)
> 
> If using cloudflare need add extra check since, cloudflare gives client ip through other variable. Script what posted gives fix for it. Of course you can make extra security check to check if info comes from cloudflare servers.

Ah, yep you're right. I glossed right over that for some reason, sorry!

I'll set up a PR tonight or tomorrow :)

**Comment by Devtodays** [comment]
I'm getting an error with the CHMOD perms saying they need to be 777 but I've already set them to 777 and I've triple checked

**Comment by JoeGandy** [comment]
Added PR #45 to address ip issue for future :)
