### ISSUE TITLE
URL is empty

### ISSUE THREAD

**Issue by g0dzcsgo** [JoeGandy/ShareX-Custom-Upload#44]
Im having issues making this work, i had a working one of these before... but now i have reset my computer.. and now i can't seem to get it to work... i've done the exact same thing 1:1 i did before..

But now it just throws me the error URL is empty...? did sharex add something new you gotta add?

IMG:
![111](https://user-images.githubusercontent.com/45868344/61844194-da2da100-ae9e-11e9-8a36-50c15e10a017.PNG)

Also, i wanna add i cannot get gallery to work... i've allowed all ips (no luck) and i've allowed my ip (no luck) anyway.

**Comment by JoeGandy** [comment]
Hi,

I'm sure we can fix this stuff, I'd recommend making sure you have the latest codebase on master, then re-follow the main setup instructions as it now includes a config auto generator.

It looks like you're on a old version of shareX too, so update that to the latest. An example config screen is here: 
![07 07 05-25 07 19 1](https://user-images.githubusercontent.com/1647362/61849955-d6a01700-aeaa-11e9-8532-4d79ae9eb3f0.png)

**Comment by g0dzcsgo** [comment]
Did as you said, still same error.... :/

IMG:
![image](https://user-images.githubusercontent.com/45868344/61851293-d279f680-aeb6-11e9-861e-fb68b3041df7.png)

**Comment by JoeGandy** [comment]
Could I have a look at your config.php? Just hide out any sensitive info and leave the ends of urls visible :)

**Comment by g0dzcsgo** [comment]
Here.
![image](https://user-images.githubusercontent.com/45868344/61852799-9e083980-aeba-11e9-902b-a7706ca3ab4a.png)

**Comment by JoeGandy** [comment]
That all looks fine, I would check these thing in order:


- Swap the config on shareX to use a https url instead of http (we'll add this to the todo automatically)
- Ensure your https cert is setup correctly
- Ensure you can add a normal index.php
- Ensure write permissions are on the /u/ directory
- Check nginx error log, as imagine the real error is being suppressed.

**Comment by g0dzcsgo** [comment]
I do not use nginx, i use cpanel.

Write perms are 777 on the /u/ directory.

My https is working correctly and is setup.

and ill try the https thing now

**Comment by g0dzcsgo** [comment]
HTTPs thing did not work.

**Comment by g0dzcsgo** [comment]
![image](https://user-images.githubusercontent.com/45868344/61853576-85008800-aebc-11e9-889e-92b5835ff0ff.png)

**Comment by g0dzcsgo** [comment]
Hello World did work correctly, and printed "Hello World", I even tried to swap all urls to http instead, still no luck... don't even know what "URL is empty" means... :/

**Comment by JoeGandy** [comment]
Hey, The error 'URL is empty' is an error from ShareX, it does this when it sends a post request but gets nothing back. This is usually an error on the server side.

I'm not familiar with cPanel, can you check for an error log or something?

The default apache error logs are here: /var/log/apache2/error.log.

nginx error logs are here: /var/log/nginx/nginx_error.log
or here: /var/log/nginx/error.log

apache/nginx are the HTTP servers, one of these will be running your website, I'm not sure how familiar you are with this stuff so apologies if i sound patronising! :)

**Comment by g0dzcsgo** [comment]
maybe i have done something wrong then.... cuz it's worked on this host before so... :/

**Comment by JoeGandy** [comment]
I'm sure its something minor, or even a mistake with the latest release, If we can track down the error in the logs, it'll tell us whats going on!

**Comment by JoeGandy** [comment]
I've found this:

https://www.liquidweb.com/kb/locations-of-common-log-files-on-cpanel-servers/

Which might be helpful for finding the error log

**Comment by g0dzcsgo** [comment]
I tried on another ftp server not hosted by the same company, and now it is actually giving no error, but not uploading any image, but instead providing a bunch of html code.

**Comment by g0dzcsgo** [comment]
![image](https://user-images.githubusercontent.com/45868344/61858574-9fd7fa00-aec6-11e9-9fcf-958fedc16d6c.png)

**Comment by g0dzcsgo** [comment]
![image](https://user-images.githubusercontent.com/45868344/61858629-b7af7e00-aec6-11e9-8665-c8604d5bacd9.png)

**Comment by JoeGandy** [comment]
Looks like you're being redirected back to the homepage, this only happens when the key passed into the post doesn't exists, or doesn't match the 'secure_key' in your config file

**Comment by g0dzcsgo** [comment]
I downloaded the file provided on the url /u/ directory
![image](https://user-images.githubusercontent.com/45868344/61858867-3efcf180-aec7-11e9-8fa8-b2cc13c1e28e.png)

But its returning HTML code....?

**Comment by g0dzcsgo** [comment]
It should match, i downloaded the file from the /u/ directory??

**Comment by JoeGandy** [comment]
In your config.php, swap out the 'http' for 'https' as I see on your site you have it forced https, this is the fix I said we need to look into :)

**Comment by g0dzcsgo** [comment]
Yep works, still my other domain doesn't work which is sad....

**Comment by g0dzcsgo** [comment]
And i wonder what the issue is, since it's worked before on there :/

**Comment by JoeGandy** [comment]
Were you able to locate the error log? As that will give us a clear picture?

**Comment by g0dzcsgo** [comment]
I don't have access to it unfortunately.

**Comment by g0dzcsgo** [comment]
It's shared hosting.

**Comment by DJkikisa** [comment]
All shared hostings normaly when you open FTP has logs folder.

**Comment by g0dzcsgo** [comment]
I do not have any error_log

**Comment by JoeGandy** [comment]
I don't think there is much we can do then, I'd get a ticket into cpanel and ask them where you can find it. If you get the error then come back here I'm sure we can help you out.

There will be some kind of error log, might be in the GUI somewhere.

**Comment by g0dzcsgo** [comment]
Ok.

**Comment by JoeGandy** [comment]
Feel free to reopen if you get more info
