### ISSUE TITLE
When a site uses https, ensure everything is set properly in configs and auto generated shareX import

### ISSUE THREAD

**Issue by JoeGandy** [JoeGandy/ShareX-Custom-Upload#47]

**Comment by DJkikisa** [comment]
`    if( isset($_SERVER['HTTPS'] ) && 'on') {
if (strpos($config['request_url'], 'https') === false) {
$config['request_url'] = str_replace("http","https",$config['request_url']);
}
}`

**Comment by JoeGandy** [comment]
We confirmed the system is working in https
