### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Adwayw4** [JoeGandy/ShareX-Custom-Upload#5]
I keep getting this error: (404) The Remote Server returned an error (404) Not found

**Comment by JoeGandy** [comment]
Hi, sorry for the delay,
Are you sure you've set up your web server correcting with the config?
Perhaps provide your config.php and we can see where the errors are? (remove the 'secure_key'

**Comment by nickm324** [comment]
I have 2 computers this is setup on, both use the exact same sxcu file for configuration. One computer works fine and on the other when I capture an image and it tries to upload, I instantly get a 404 error, yet it works perfectly from the other computer.
After looking at the destination custom upload configs, they are identical.

What is the issue?
