### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by g0dzcsgo** [JoeGandy/ShareX-Custom-Upload#51]
Currently i use "%rn%ra%rn%ra%rn%ra%rn%ra%rn%ra%rn%ra" for a random name, before it used to show all alternatives you could do when hovering over the column, but it no longer does this.. so can anyone with knowledge on this write all name random syntaxes or whatever it's called here?

**Comment by DJkikisa** [comment]
You can still get all under: Task Settings > Upload > File Naming. And there when press on input they show all options.
