### ISSUE TITLE
Upload to root of domain

### ISSUE THREAD

**Issue by untuned** [JoeGandy/ShareX-Custom-Upload#52]
Instead of <domain>/u/image.png, I'd rather have <domain>/image.png.  Is this possible?

**Comment by DJkikisa** [comment]
You need edit upload.php file, but yea you can.

**Comment by untuned** [comment]
> You need edit upload.php file, but yea you can.

What would I edit?

**Comment by JoeGandy** [comment]
Maybe we can add this to config.php as a option as its requested a lot, we could have two options:

upload_to_root => true/false,
directory_for_uploads => 'u' // Would be u to match default.

I'll leave this open encase anyway wants to do a PR for it, else I'll get around to it 'at some point' :)

**Comment by DJkikisa** [comment]
Or just set domain what you want for that folder with VirtualHost.

**Comment by untuned** [comment]
> Maybe we can add this to config.php as a option as its requested a lot, we could have two options:
> 
> upload_to_root => true/false,
> directory_for_uploads => 'u' // Would be u to match default.
> 
> I'll leave this open encase anyway wants to do a PR for it, else I'll get around to it 'at some point' :)

add the "help wanted" label, so people see it as something they can do to help

**Comment by jnthn-b** [comment]
Would be some pretty big change, due to the current config not even giving you the option tho change the directory for uploads. The '/u/' Value is hard coded into the upload file, and not loaded from the config file. So what we would have to change:
- adding target directory into the config
- loading directory from config (in the upload file)

So what are we doing with the gallery page? We would have to move all the files from the u directory into the target directory or even the root directory.
I might take a look at this and try to add (some) functions.

**Comment by JoeGandy** [comment]
> Would be some pretty big change, due to the current config not even giving you the option tho change the directory for uploads. The '/u/' Value is hard coded into the upload file, and not loaded from the config file. So what we would have to change:
> 
> * adding target directory into the config
> * loading directory from config (in the upload file)
> 
> So what are we doing with the gallery page? We would have to move all the files from the u directory into the target directory or even the root directory.
> I might take a look at this and try to add (some) functions.
We need to think about the main gallery page, but in theory it can exist in the same directory as the root of the site if uploads are there? 

Current site structure is:
u/ -> Upload root, this contains index.php to display the gallery
There is no reason this can't be anywhere?

**Comment by jnthn-b** [comment]
Yeah but the user has to move the files around manually. Still it can be set, values in the upload file have to been grabbed from the config file.
other idea: 
files still get uploaded to u/, but the gallery is in the root folder and loads the images from the u/ directory?!

**Comment by jnthn-b** [comment]
Okay I modified the Config and the Upload file, that should be all right? 
And if the changes get added we have to edit the read me file!

**Comment by JoeGandy** [comment]
Handled by #55 After the conflicts are resolved

**Comment by theaquarium** [comment]
This has been added in Version 2. The upload is in root by default now, and although files are uploaded to the `u` folder, they are now accessible from root.
