### ISSUE TITLE
URL: You may not upload without the key parameter, see full config: 

### ISSUE THREAD

**Issue by MikeLinssen** [JoeGandy/ShareX-Custom-Upload#53]
I'm sure I've done everything correctly. Because I had a way older version I downloaded this updates version but now I get this error?

Using HTTPS and changed every /u/ to / because I use the root directory, pretty sure I've set it up correctly but I just keep getting this error, no matter what I do.

Hopefully someone can help.

**Comment by Kavalll** [comment]
I've got the same and hopefully @JoeGandy still cares about this.
Has something to do with HTTPS since I can use the script on my other sites that don't have it.

**Comment by JoeGandy** [comment]
Sorry, yep this has fallen off my radar recently,

but I'll pick it up this week.

**Comment by JoeGandy** [comment]
Hi I've just confirmed functionality is working,

I have a site set up with https, using the u/ custom directory
I have a 301 redirect from http version of the site to https

I download the config generated by the web ui

Test an image upload which works. If yo have anymore details on how to reproduce let me know.

(This is from a previous test on another issue) So if anything else isn't working it may be to do with the custom changes you've made to the upload directory, perhaps make a feature request to specify the directory in the config.php and someone can pick it up.

Or do a PR once you've figured it out :)
