### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by noah-34** [JoeGandy/ShareX-Custom-Upload#56]
I get this output: 

`

> URL: <html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("7949e2c5384cefd2781566deca08606c");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://images-da-bald-eagul.ga/ShareX-Custom-Upload-master/src/upload.php?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

`
is there anything I need to change in ShareX?

**Comment by JoeGandy** [comment]
Did you find a solution to this?

It looks like you may have something around the webserver enforcing js?

**Comment by JoeGandy** [comment]
I'll close it for now, but do feel free to reopen if there is anything else to report.
