### ISSUE TITLE
Break apart logic for abstraction + unit tests

### ISSUE THREAD

**Issue by JoeGandy** [JoeGandy/ShareX-Custom-Upload#58]
Break apart various parts of the upload process.

- Getting config
- Getting target dir (in new feature)
- Uploading files

Once we isolate the logic we can wrap it in unit tests, this would speed up the PR process in the future

**Comment by JoeGandy** [comment]
Using: https://github.com/marketplace/actions/phpunit-php-actions
and github actions: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

We should be able to implement this onto PRs

**Comment by JoeGandy** [comment]
This PR contains the work:
https://github.com/JoeGandy/ShareX-Custom-Upload/pulls

**Comment by untuned** [comment]
can be closed
