### ISSUE TITLE
[FIXED] Not changing link when uploading

### ISSUE THREAD

**Issue by brandon14Coding** [JoeGandy/ShareX-Custom-Upload#6]
ive tried it a few times and its not changing the link http://i.imgur.com/uZHhYgm.png the only way to change it is going into the custom uploading settings and changing the arguments

Any help appreciated

**Comment by JoeGandy** [comment]
Hi this is how its intended so anyone can use whatever naming scheme they like for the files, see the instructions here:
`1. From the ShareX main application we go to Destinations > Destination Settings
2. Scroll down to 'custom uploaders' add a new profile
3. Request type POST, the url should be http://www.example.com/upload.php
4. File from name `d'
5. Arguments are:
    - key, this should be set to the 'secure key' you set in your config.php
    - name, this is how the files will be named, for mine, i use '%h.%mi.%s-%d.%mo.%yy'
6. The setup is now complete, test your uploader and it 'should' work!`

Focusing on this line: 
`   - name, this is how the files will be named, for mine, i use '%h.%mi.%s-%d.%mo.%yy'`

The idea behind this is to

1. Keep the tool as simple to use as possible
2. Allows the user to configure whatever naming they want (ShareX includes other ways to rename files such as random numbers, computer names etc)

Let me know if you need anymore info
