### ISSUE TITLE
Too few arguments to function get_file_target

### ISSUE THREAD

**Issue by Tsundere-Mailbox** [JoeGandy/ShareX-Custom-Upload#60]
Hey, I've been trying to set up this file uploader for a little while now, however no matter what I do it never works. I've followed the instructions to a T yet it still doesn't work. I will admit that I don't really have much, or any for that experience with any of this so I very well may be doing something. A little bit of help would be wonderfully helpful. 

Here's the info I've got.

<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught ArgumentCountError: Too few arguments to function get_file_target(), 2 passed in D:\wamp64\www\upload.php on line 16 and exactly 3 expected in D:\wamp64\www\u\functions.php on line <i>27</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> ArgumentCountError: Too few arguments to function get_file_target(), 2 passed in D:\wamp64\www\upload.php on line 16 and exactly 3 expected in D:\wamp64\www\u\functions.php on line <i>27</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>400472</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='D:\wamp64\www\upload.php' bgcolor='#eeeeec'>...\upload.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>400512</td><td bgcolor='#eeeeec'>get_file_target(  )</td><td title='D:\wamp64\www\upload.php' bgcolor='#eeeeec'>...\upload.php<b>:</b>16</td></tr>
</table></font>

Thanks a ton, sorry if it's just something simple I'm messing up. >.<

**Comment by JoeGandy** [comment]
Hi,

Thanks for spotting this, there was definitely something wrong in the repo, oddly enough i made the change locally but missed it off the PR. Thats my mistake. Here is the hotfix i put in place: 
https://github.com/JoeGandy/ShareX-Custom-Upload/commit/cbdb3d609fada88c401d4844c5a35c426d43b3f9#diff-2f3c88ea110efbfb40f20a20f4cec143

Just update your local copy and it should all be fixed!
Thanks for reporting it!
