### ISSUE TITLE
Deleting file redirects to homepage?

### ISSUE THREAD

**Issue by silent** [JoeGandy/ShareX-Custom-Upload#61]
When I delete files in the gallery it automatically redirects me to my domain homepage vs staying on the gallery page. How can I stop this redirection?

Below is an example of what my configuration file looks like:

`    /* This is a secure key that only you should know, an added layer of security for the image upload */
    'secure_key' => 'MYKEYHERE',

    /* This is the url your output will be, usually http://www.domain.com/u/, also going to this url will be the gallery page */
    'output_url' => 'https://mydomain.com/u/',

    /* This request url, so the path pointing to the uplaod.php file */
    'request_url' => 'https://mydomain.com/upload.php',

    /* This is a redirect url if the script is accessed directly */
    'redirect_url' => 'https://mydomain.com/u/',

    /* This is a list of IPs that can access the gallery page (Leave empty for universal access) */
    'allowed_ips' => ['127.0.0.1', '::1', '0.0.0.0'],

    /* Page title of the gallery page */
    'page_title' => 'My Upload Site',

    /* Heading text at the top of the gallery page */
    'heading_text' => 'My Site',

    /* Delete file option (true to enable, disabled by default) */
    'enable_delete' => true,

    /* Show image in tooltip  (true to enable, disabled by default) */
    'enable_tooltip' => true,

    /* Show link to download all files as .zip (Untested with large archives of files) */
    'enable_zip_dump' => false,

    /* Generate random name (true to enable, disabled by default) */
    'enable_random_name' => true,

    /* Select lenght of random name (10 symbols by default) */
    'random_name_length' => 10,`

**Comment by Jespertastesen** [comment]
change: `die(header('Location:/'`
to: `die(header('Location:'.$config['output_url']));`

this now redirects you to the right page.

**Comment by JoeGandy** [comment]
Resolved in #62
