### ISSUE TITLE
Shows info when you don't have access

### ISSUE THREAD

**Issue by S-Sal73** [JoeGandy/ShareX-Custom-Upload#68]
When your IP is not whitelisted it will still show the user who doesn't have access the free space of the website.
http://83575.aoweb.nl/u/B6aW9gc4DO.png

**Comment by JoeGandy** [comment]
Ah I know what you're describing, 
I don't think it was intended as a bug, as was more of a 'what is the harm in showing it'
But yeah you're right I'll open up a PR to address it soon.

**Comment by Jespertastesen** [comment]
#70

**Comment by JoeGandy** [comment]
Now fixed thanks to @Jespertastesen Apologies for the delay reviewing
