### ISSUE TITLE
sorting by date sorts by number, not month

### ISSUE THREAD

**Issue by untuned** [JoeGandy/ShareX-Custom-Upload#69]
this image should show enough
![](https://i.untuned.me/8vrjKYRJ)

**Comment by Jespertastesen** [comment]
That is a issue with the config of the DataTables used in the system.
might be a simple fix ?

**Comment by JoeGandy** [comment]
Agreed it could be a really simple fix, so will see if i can get around to it soon

**Comment by JoeGandy** [comment]
Thanks @DJkikisa for the quick fix! :)
