### ISSUE TITLE
Add a delete all option

### ISSUE THREAD

**Issue by bokerlol** [JoeGandy/ShareX-Custom-Upload#73]
Would it be possible to have a purge/delete all images option? I like having my own ShareX Custom Uploader but disk space will be a problem long term and i'd rather not manually delete them all or FTP into the server to manually delete them.

**Comment by JoeGandy** [comment]
This makes sense to me, 

I'll see what i can do about getting a PR setup for it soon, but will open it up to anyone else too

**Comment by bokerlol** [comment]
Thank you!

**Comment by theaquarium** [comment]
This has been added in Version 2.
