### ISSUE TITLE
You may not upload without the key parameter

### ISSUE THREAD

**Issue by Stage4000** [JoeGandy/ShareX-Custom-Upload#74]
I have downloaded the automatic import script and everything but i still get this error when i attempt to test the settings. I checked the settings manually and they all seem correct from both ends but still getting the error.

**Comment by bokerlol** [comment]
Just an idea but I was getting this error when I was going above my max upload limit for the php script. Have you double checked to make sure you aren't going above that limit?

**Comment by Stage4000** [comment]
Yeah im sure that 8kb < 200mb

**Comment by Stage4000** [comment]
I ended up using another script that I found from another user that had the same issue with this one. I would prefer to use this one though.

**Comment by crsncc** [comment]
Is the key parameter blank?

**Comment by Stage4000** [comment]
Nope. Way to take a month to respond with a dumb question. The script sucks, I moved on.
