### ISSUE TITLE
You may not upload without the key parameter, see full config

### ISSUE THREAD

**Issue by DestruktorGitHub** [JoeGandy/ShareX-Custom-Upload#77]
Hi,I have a little problem with this shareX script. Every Time I want to upload screenshot I got this communicate.

"You may not upload without the key parameter, see full config: https://github.com/JoeGandy/ShareX-Custom-Upload/blob/master/README.md#automatic-setup"

![ss1](https://user-images.githubusercontent.com/41994615/79323150-1bbf1a00-7f0e-11ea-88d9-33da3ba51263.jpg)

**Comment by crsncc** [comment]
Yeah it's above the output URL

**Comment by DestruktorGitHub** [comment]
I know, but whatever I wrote there I always had the same message.

**Comment by crsncc** [comment]
If you could contact me on discord so I can help you that would be great. [:)](https://crsn.cc/)

**Comment by DestruktorGitHub** [comment]
Sure, Destruktor#2020 that's my nickname with tag.

**Comment by awildcharlotte** [comment]
I am experiencing the same issue.

**Comment by JoeGandy** [comment]
Did you have any luck, would be worth noting the issue down so we can start creating a known issues page or address the problems.

**Comment by DestruktorGitHub** [comment]
No, sorry but I still waiting for conversation with @crsncc

**Comment by crsncc** [comment]
@JoeGandy Maybe you could start a support discord and if people have problems you or someone with some the knowledge can help. If you need help with setting up one I am more than happy to.

**Comment by DestruktorGitHub** [comment]
I know only that the problem is because my SSL protocol. When I copied my script into my other domain without SSL, everything starts work fine.

**Comment by JoeGandy** [comment]
It seems to work fine on my own site with https, so not sure what causes it on your end, im using letsencrypt for the cert

**Comment by DJkikisa** [comment]
I'm using Cloudflare ssl and have 0 problems.

**Comment by JoeGandy** [comment]
> I know only that the problem is because my SSL protocol. When I copied my script into my other domain without SSL, everything starts work fine.

Do you have any more info that may help us, is it apache2, nginx, a shared host? Where is your SSL Cert from?

**Comment by theaquarium** [comment]
My friend also told me that he was having problems with accessing `upload.php` through SSL, but I'm not really sure what the details are and it seems like in this case, it was just a configuration error. I'm closing this for now.

About a support Discord, I love the idea, but I'm not sure if this project has that kind of scale yet where that's necessary :)
However, maybe we'll make one in the future.
