### ISSUE TITLE
Large file uploads fail

### ISSUE THREAD

**Issue by Sharkiiie** [JoeGandy/ShareX-Custom-Upload#8]
When uploading a large file (about 2MB or larger) it puts an error in your clipboard.

`Sorry, there was a problem uploading your file. (Ensure your directory has 777 permissions)`

On some files, it will just copy the index.html contents to your clipboard. 
I'm not super pro, so it could be an error with my server, but I've increased the max upload sizes, exec time, etc.

**Comment by JoeGandy** [comment]
Hi,
I ran into this initial and you just need to increase `upload_max_filesize` in your php.ini

It defaults at 2M

**Comment by Sharkiiie** [comment]
I feel a bit silly now.
I changed the variables in the php.ini, but apache was loading extra .ini files.

The solution was to make a new file "root.ini" and put in the max filesize and max post vars in there, which makes apache use that.
Not sure why that's the case, but I thought I'd let you know in case anyone else has the same issue.

**Comment by JoeGandy** [comment]
Okay great, glad you were able to fix it.

and thanks for posting the solution 👍
