### ISSUE TITLE
Upload gallery mostly blank

### ISSUE THREAD

**Issue by dala420** [JoeGandy/ShareX-Custom-Upload#80]
When I go to my website/u/ it's just a white page with the text "Uploading site" at the top and under it say's "Free space: 95.15 GB / 139.21 GB " (which is wrong) images upload fine but I just can't browse them.

I put the "u" folder and upload.php from inside src into the root of my site.

If I take my IP out of the config.php then nothing changes except it adds the text: "Your IP is blocked from access, whitelist this ip to gain access: (my ip)"

![gallery](https://user-images.githubusercontent.com/6685758/83318346-dc603a80-a1e8-11ea-9e5c-a5519dfc6484.png)

**Comment by JoeGandy** [comment]
Do you get any console errors, wondering if something is failing front end wise?

**Comment by CJsea** [comment]
Make sure you put in your domain correctly

**Comment by theaquarium** [comment]
If you're still getting this issue, could you send over your config? This may have something to do with invalid URLs configured, as Carson said.
