### ISSUE TITLE
Version 2 issue

### ISSUE THREAD

**Issue by silent** [JoeGandy/ShareX-Custom-Upload#85]
Parse error: syntax error, unexpected ')' in /home/websitename/public_html/u/functions.php on line 126
What to do?

**Comment by theaquarium** [comment]
What version of PHP are you running?

**Comment by theaquarium** [comment]
Oh, nevermind, this is an error on my part. The release ZIP currently contains an old version of the code. I've updated the release, so you can just download the ZIP again. Sorry about that.

**Comment by theaquarium** [comment]
Please let me know if it is fixed.

**Comment by silent** [comment]
This issue has been resolved. Love the new update so far. Can't wait to see more updates to this!
