### ISSUE TITLE
Since v2, if you disable 'enable_gallery_page_uploads' => false, it borks JS

### ISSUE THREAD

**Issue by JoeGandy** [JoeGandy/ShareX-Custom-Upload#89]
` 'enable_gallery_page_uploads' => false,     `
disabling this, as for me personally it takes up half the screen.

This breaks JS, its prob not checking for undefined on:
`if (Dropzone) {`

**Comment by theaquarium** [comment]
You're right, I probably should have tested this. Now it checks if `window.Dropzone` exists, which doesn't throw.
