### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by FORSCOM** [JoeGandy/ShareX-Custom-Upload#9]
Keep getting this error. Followed the instructions.

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by JoeGandy** [comment]
Can you print screen your settings on ShareX and your config.php settings? Blurring out any domains/keys

**Comment by FORSCOM** [comment]
![be44a89e](https://user-images.githubusercontent.com/23144866/32661610-3071bc5a-c5ed-11e7-90d6-50618da1dd98.png)
![9752f38d](https://user-images.githubusercontent.com/23144866/32661612-31887c1e-c5ed-11e7-8f53-856eb65922ac.png)

**Comment by FORSCOM** [comment]
?

**Comment by JoeGandy** [comment]
Sorry for the delay, I try to help as quick as I can...

Can you confirm this is the only response you are getting.

Usually when ShareX gives a error message, you get a message, request url, response, stack tract.

You've provided just the stack trace which doesn't tell me too much sadly

Maybe print screen the error as it appears to you?

Please check for any error logs in your ShareX folder which defaults to:

C:\Users\YOURUSERNAME\Documents\ShareX
