### ISSUE TITLE
Automatic Updater Script

### ISSUE THREAD

**Issue by theaquarium** [JoeGandy/ShareX-Custom-Upload#95]
I was thinking about how a user could update to a newer version of the uploader and it seems like it would require a lot of manual work, such as deleting all of the old project files but keeping their config and uploads, then selectively copying the code files for the new version. What if instead, this was done through some sort of automatic updater script? For example, since releases now come packaged in a folder called `release`, all a user would need to do to update their uploader would be to copy this entire release folder into their current uploader. Then, the next time the user opened the gallery page, the uploader would check if there's a folder called `release` present, and if there is, it would prompt to update to a new version of the uploader. If the user says yes, it would open a PHP page called `updater.php` located *in the new `release` folder*. The update script would then copy files from the release folder and overwrite them in the main uploader, but only for non-user configurable files. Then, all the user would have to do would be to delete the release folder.

For example, if a user set up their uploader in a folder called `/my/website/root/`:
1. The user copies the `release` folder from the new version into `/my/website/root/release/`
2. The user opens up their gallery page at `http://mywebsite.com` and it shows an Update button
3. The user presses update, which sends the user to `http://mywebsite.com/release/updater.php`
4. This script overwrites the project code in `/my/website/root/` with the new code from `/my/website/root/release/` but keeps the old config files
5. The user deletes the `/my/website/root/release` folder

This would hopefully provide a more streamlined update process. Let me know what you think. I'd be happy to work on this.

**Comment by silent** [comment]
This would make updating a lot easier or at least in the changelog add what files were changed that way it can be easier to know which files to drag over vs all.
